const { chromium } = require('playwright');
const OUT = process.env.OUT || '.';
const W = +(process.env.W || 390), H = +(process.env.H || 844);
const LOCALE = process.env.LOC || 'ja-JP';
const SCHEME = process.env.SCHEME || 'dark';
const TAG = process.env.TAG || `${LOCALE.slice(0,2)}-${SCHEME}-${W}`;
const ONLY = process.env.ONLY;
(async () => {
  const b = await chromium.launch();
  const ctx = await b.newContext({ viewport: { width: W, height: H }, deviceScaleFactor: 2, locale: LOCALE, colorScheme: SCHEME });
  const p = await ctx.newPage();
  const errors = [];
  p.on('pageerror', (e) => errors.push('pageerror: ' + e.message));
  p.on('console', (m) => { if (m.type() === 'error') errors.push('console: ' + m.text()); });
  p.on('dialog', (d) => { console.log('dialog: ' + d.message().replace(/\n/g, ' / ')); void d.dismiss(); });
  const shot = async (name) => { await p.waitForTimeout(400); await p.screenshot({ path: `${OUT}/${TAG}-${name}.png` }); console.log('shot', name); };
  const tap = async (text, opts = {}) => { const l = p.getByText(text, { exact: opts.exact ?? true }).first(); await l.click(); await p.waitForTimeout(opts.wait ?? 500); };
  const tapLabel = async (label) => { await p.getByLabel(label, { exact: true }).first().click(); await p.waitForTimeout(500); };
  const ja = LOCALE.startsWith('ja');
  const T = (j, e) => (ja ? j : e);
  await p.goto(`http://localhost:8765/?speed=${process.env.SPEED || 60}${process.env.Q || ''}`);
  await p.waitForTimeout(2500);
  if (SCHEME === 'light') {
    await tapLabel(T('設定', 'Settings'));
    await tap(T('ライト', 'Light'), { wait: 800 });
    await p.locator('[aria-label$="back"]').first().click(); await p.waitForTimeout(500);
    await p.waitForTimeout(800);
  }
  await shot('01-home-empty');
  if (ONLY === 'home') { console.log(errors.join('\n')); await b.close(); return; }
  await tap(T('新しいエピソードを録る', 'Record a new episode'), { wait: 1500 });
  await shot('02-record-idle');
  await tapLabel(T('録音を開始', 'Start recording'));
  await p.waitForTimeout(2600);
  await shot('03-recording');
  await tapLabel(T('一時停止', 'Pause'));
  await shot('04-paused');
  await tapLabel(T('再開', 'Resume'));
  await p.waitForTimeout(1500);
  await tapLabel(T('収録を終える', 'Finish take'));
  await p.waitForTimeout(1500);
  await shot('05-stopped');
  await p.getByRole('tab', { name: T('編集', 'Edit') }).click();
  await p.waitForTimeout(1200);
  await shot('06-edit');
  const lane = await p.getByText(T('素材なし', 'No sounds'), { exact: true }).first().boundingBox();
  await p.mouse.click(lane.x + 100, lane.y - 60); await p.waitForTimeout(900);
  await shot('07-edit-selection');
  await tap(T('選択をカット', 'Cut selection'), { wait: 900 });
  await shot('08-cut-toast');
  await tap(T('取り消す', 'Undo'), { wait: 1200 });
  await shot('08b-undone');
  await p.getByRole('tab', { name: T('書き出し', 'Export') }).click();
  await p.waitForTimeout(1200);
  await shot('09-export');
  await p.mouse.wheel(0, 3000); await p.waitForTimeout(500);
  await shot('10-export-bottom');
  await tap(T('音声を書き出す', 'Export audio'), { wait: 1200 });
  await shot('11-export-progress');
  await p.waitForTimeout(3500);
  await shot('12-handoff');
  await p.getByText(T('コピー', 'Copy'), { exact: true }).nth(1).click(); await p.waitForTimeout(300);
  await shot('13-handoff-copied');
  await tap(T('エピソード一覧へ', 'Back to episodes'), { wait: 1500 });
  await shot('14-home-data');
  await tapLabel(T('設定', 'Settings'));
  await shot('15-settings');
  await p.goBack(); await p.waitForTimeout(800);
  await tap(T('番組と素材', 'Show & assets'), { wait: 1200 });
  await shot('16-show');
  console.log('ERRORS:\n' + errors.join('\n'));
  await b.close();
})().catch((e) => { console.error(e); process.exit(1); });
