// デザイントークンの入口。画面と `ui/` はここからだけ読む（DESIGN_SYSTEM.md §1）。
export { colors, type Colors, type ThemeName } from './colors';
export { tone, type Tone, type ToneName } from './tones';
export {
  chip,
  grabber,
  gutterNowPlaying,
  pill,
  shadow,
  artwork,
  avatar,
  quickTile,
  compactWidth,
  concentric,
  dialogWidth,
  family,
  field,
  fieldPadding,
  glyphSlop,
  gutter,
  gutterCompact,
  hit,
  hitSlop,
  icon,
  motion,
  player,
  pressScale,
  pressedOpacity,
  radius,
  recordView,
  space,
  stroke,
  timeline,
  tabularNums,
  typography,
  wordmarkSize,
  type FamilyRole,
  type TypeRole,
} from './scale';
